lint blue falling

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -21,12 +21,12 @@ jobs:
           name: Lint Blue Environment
           command: |
             hadolint ./BlueEnvironment/Dockerfile | tee -a docker_lint_blue.txt
-            checkLintBlue=`stat --printf="%s"  docker_lint_blue.txt`
+            checkLintBlue=`stat --printf="%s"  docker_lint_blue.txt
                     
             if [ "$checkLintBlue" -gexit "0" ]
-            then
-                echo "Error"
-                exit 1
+              then
+                  echo "Error"
+                  exit 1
             else
                 echo "Blue Environment Successful"
             fi
